// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL bevorzugt (Verbindung ohne Pooler, nötig für Schemaänderungen).
    // Ist sie nicht gesetzt, DATABASE_URL nehmen, damit Migrationen auch dort
    // laufen, wo es nur diese eine Variable gibt (z.B. im Vercel-Build).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
